# Generated by Django 5.2.1 on 2025-12-03 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('kode_akun', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_akun', models.CharField(max_length=255)),
                ('kategori', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jurnal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('keterangan', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JurnalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('kredit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laporan_keuangan.akun')),
                ('jurnal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='laporan_keuangan.jurnal')),
            ],
        ),
    ]
