# Generated by Django 5.2.1 on 2025-12-05 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('kode_akun', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=200)),
                ('kategori', models.CharField(choices=[('ASET', 'Aset'), ('KEWAJIBAN', 'Kewajiban'), ('EKUITAS', 'Ekuitas'), ('PENDAPATAN', 'Pendapatan'), ('BEBAN', 'Beban'), ('ARUS_KAS', 'Arus Kas')], max_length=30)),
                ('normal_balance', models.CharField(choices=[('DEBIT', 'Debit'), ('KREDIT', 'Kredit')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Jurnal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('keterangan', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('sumber', models.CharField(blank=True, max_length=50)),
                ('is_posted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JurnalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('kredit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('keterangan', models.CharField(blank=True, max_length=200)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laporan_keuangan.akun')),
                ('jurnal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='laporan_keuangan.jurnal')),
            ],
        ),
    ]
