# Generated by Django 5.2.1 on 2025-12-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan_keuangan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_akun', models.CharField(max_length=10, unique=True)),
                ('nama_akun', models.CharField(max_length=255)),
                ('kategori', models.CharField(choices=[('ASET', 'Aset'), ('LIABILITAS', 'Liabilitas'), ('EKUITAS', 'Ekuitas'), ('PENDAPATAN', 'Pendapatan'), ('BEBAN', 'Beban'), ('DIVIDEN', 'Dividen'), ('ARUS_KAS', 'Arus Kas')], max_length=20)),
                ('saldo_normal', models.CharField(choices=[('DEBIT', 'Debit'), ('KREDIT', 'Kredit')], max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='jurnalitem',
            name='akun',
        ),
        migrations.RemoveField(
            model_name='jurnalitem',
            name='jurnal',
        ),
        migrations.DeleteModel(
            name='Akun',
        ),
        migrations.DeleteModel(
            name='Jurnal',
        ),
        migrations.DeleteModel(
            name='JurnalItem',
        ),
    ]
