# Generated by Django 5.2.1 on 2025-12-16 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan_keuangan', '0002_chartofaccount_remove_jurnalitem_akun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JurnalUmum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('kredit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('keterangan', models.CharField(max_length=255)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laporan_keuangan.chartofaccount')),
            ],
        ),
    ]
