# Generated by Django 5.2.1 on 2025-12-16 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan_keuangan', '0003_jurnalumum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurnal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('keterangan', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JurnalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('kredit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laporan_keuangan.chartofaccount')),
                ('jurnal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='laporan_keuangan.jurnal')),
            ],
        ),
        migrations.DeleteModel(
            name='JurnalUmum',
        ),
    ]
