# Generated by Django 5.2.1 on 2025-12-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan_keuangan', '0004_jurnal_jurnaldetail_delete_jurnalumum'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnal',
            name='jenis',
            field=models.CharField(choices=[('OPENING', 'Jurnal Pembuka'), ('GENERAL', 'Jurnal Umum')], default='GENERAL', max_length=10),
        ),
    ]
