# Generated by Django 5.2.1 on 2025-12-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan_keuangan', '0005_jurnal_jenis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
