# Generated by Django 5.2.1 on 2025-12-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan_keuangan', '0006_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurnal',
            name='jenis',
            field=models.CharField(choices=[('OPENING', 'Jurnal Pembuka'), ('GENERAL', 'Jurnal Umum'), ('CLOSING', 'Jurnal Penutup')], default='GENERAL', max_length=10),
        ),
    ]
